version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "python"
    groups:
      python:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "extension"
    groups:
      extension:
        patterns:
          - "*"
